"""Add iban

Revision ID: 81a9f56fc2ec
Revises: b0d2cf7b44ca
Create Date: 2023-03-13 18:12:30.686286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81a9f56fc2ec'
down_revision = 'b0d2cf7b44ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iban', sa.String(length=22), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('iban')

    # ### end Alembic commands ###
